### ISSUE TITLE
Shorter description in readme.md

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/cyberchef_ynh#1]
@oleole39 please, make the description short as it is used in the app page in the webadmin.

**Comment by oleole39** [comment]
Hello @ericgaspar 
I pushed a shorter version on the original repo. 
As just expressed [there](https://github.com/YunoHost/apps/pull/1654#issuecomment-1475321296) I am not clear on what is the expected contribution method between the fork and the main repo. Please advise.

**Comment by ericgaspar** [comment]
you have maintain role for this repo, so you should be able to work on this repo

**Comment by oleole39** [comment]
So i work on the fork directly and not on the original repo anymore, right ?
